services:
    db:
        image: mysql:latest
        container_name: 'db'
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: testdb
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: dbu$3r
            MYSQL_ROOT_PASSWORD: r00t_dbu$3r
        volumes:
            - ./data:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
volumes:
    persistent: